# Generated by ChatGPT on 2025-12-14
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="consola",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="inventario.consola"),
        ),
        migrations.AddField(
            model_name="producto",
            name="es_videojuego",
            field=models.BooleanField(default=True, help_text="Marcar si este producto es un videojuego (si lo es, se recomienda indicar la consola)."),
        ),
    ]
