# Generated by Django 5.0.6 on 2025-12-15 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_consola_opcional_es_videojuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='consola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.consola'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_videojuego',
            field=models.BooleanField(default=False),
        ),
    ]
