# Generated by Django 5.0.6 on 2025-12-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('archivo_productos', models.FileField(upload_to='propuestas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propuesta de proveedor',
                'verbose_name_plural': 'Propuestas de proveedores',
                'ordering': ['-creado'],
            },
        ),
    ]
